server {
    listen 80;
    server_name me.sacharenault.ovh;

    location / {
        alias /usr/share/nginx/html;  # Use `alias` to point directly to the built Jekyll site
        index index.html;

        # Handle pretty URLs (try to serve URI, URI as a directory, or add .html)
        try_files $uri $uri/ $uri.html =404;
    }
}